### ISSUE TITLE
019 CSS Web Font - Memberikan `font-family` pada @font-face dan contoh menggunakannya

### ISSUE THREAD

**Issue by syahid246** [bellshade/HTML-CSS#234]
Supaya fontnya dapat digunakan dan dicoba secara langsung, saya menambahkan `font-family` pada @font-face serta cara penggunaanya.

## NOTE
Saya tidak mengurangi apapun, hanya menambahkan isi pada [github.com/bellshade/HTML-CSS/CSS/019 CSS Web Font](https://github.com/bellshade/HTML-CSS/tree/main/CSS/019%20CSS%20Web%20Font).

## Commit saya
- https://github.com/syahid246/HTML-CSS/commit/fca2f03fe3e92f0d8314d2107a769d7f04a53470
- https://github.com/syahid246/HTML-CSS/commits/main/CSS/019%20CSS%20Web%20Font

## Pull
> Sedang dikerjakan

**Comment by dhafitf** [comment]
Okay, terima kasih sudah membuat issues.
Silahkan lakukan pull request.
