### ISSUE TITLE
Materi yang sama di CSS

### ISSUE THREAD

**Issue by dhafitf** [bellshade/HTML-CSS#50]
Saya menemukan materi yang sama pada folder [CSS](https://github.com/bellshade/HTML-CSS/tree/main/CSS). Saya rasa materi [Custom Properties](https://github.com/bellshade/HTML-CSS/tree/main/CSS/CSS%20Custom%20Properties) dan [Variable](https://github.com/bellshade/HTML-CSS/tree/main/CSS/CSS%20Variable) adalah materi yang sama. Apakah tidak masakah jika ada 2 materi yang sama?
Mungkin saran saya digabungkan saja menjadi 1 folder / file, supaya memudahkan orang yang akan belajar di Bellshade.

**Comment by dhafitf** [comment]
Sudah dijawab oleh om @kingramzy di PR [CSS Variable](https://github.com/bellshade/HTML-CSS/pull/45#issuecomment-934051138).

**Comment by abinoval** [comment]
I mean, although the content is slightly different, the material remains the same, only the delivery is different :)
